name: "Bug report"
description: report a bug/issue
title: "[BUG] <title>"
labels: ["Bug"]
body:
- type: markdown
  attributes:
    value: "## Welcome!"
- type: markdown
  attributes:
    value: |
      Thanks for taking the time to fill out this bug!
- type: dropdown
  id: typebug
  attributes:
    label: Type of Bug
    options:
      - Console Error
      - Tweak not working
      - Command not working
      - Something else
  validations:
    required: true
- type: textarea
  id: behavior
  attributes:
    label: Current Behavior
    description: A concise description of what you're experiencing.
  validations:
    required: true
- type: textarea
  id: expected
  attributes:
    label: Expected Behavior
    description: A concise description of what you expected to happen.
  validations:
    required: true
- type: textarea
  id: reproduce
  attributes:
    label: Steps To Reproduce
    description: Steps to reproduce the behavior.
    placeholder: |
      1. In this environment...
      1. With this config...
      1. Run '...'
      1. See error...
  validations:
    required: true
- type: input
  id: mclo.gs
  attributes:
    label: mclo.gs Link
    description: "Please copy your console log to [mclo.gs](https://mclo.gs) and enter your link here"
    placeholder: "Link"
  validations:
    required: true
- type: input
  id: servertype
  attributes:
    label: Type of Server
    description: "Spigot/Bukkit/PaperMC #Build"
    placeholder: "PaperMC #372"
  validations:
    required: true
- type: dropdown
  id: plugin
  attributes:
    label: Plugin Version
    options:
      - 1.0.0
  validations:
    required: true
- type: textarea
  attributes:
    label: Anything else?
    description: |
      Links? References? Anything that will give us more context about the issue you are encountering!
